title: Shanthi Rama # your name (or website title) here
logo: "/images/Pic.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst
  <br><br>
  Data Is The New Oil.
  <br><br>
  
  <a href="https://www.linkedin.com/in/shanthi-rama-750071217/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-0WY89FPMVE # your Google Analytics tracking ID here
